### ISSUE TITLE
404 on pulling images

### ISSUE THREAD

**Issue by jomach** [Bridg/docker-presto-server#1]
Hi, 

So I'm trying your docker image but it seems it does not work...

$ docker pull bridg/presto-server
Using default tag: latest
Pulling repository docker.io/bridg/presto-server
Network timed out while trying to connect to https://index.docker.io/v1/repositories/bridg/presto-server/images. You may want to check your internet connection or if you are behind a proxy.

docker pull bridg/presto-server:0.137
Pulling repository docker.io/bridg/presto-server
Network timed out while trying to connect to https://index.docker.io/v1/repositories/bridg/presto-server/images. You may want to check your internet connection or if you are behind a proxy.

Are you having the same issue ? 
Thanks

**Comment by ticean** [comment]
Hi @jomach! We've been using the image without problems. I confirmed that our [presto-server](https://hub.docker.com/r/bridg/presto-server/) and [java](https://hub.docker.com/r/bridg/java/) images are public and reachable. It looks like you may actually be having network problems connecting to Docker hub to pull the images.

Please try the following and let me know your results:

* Try again - perhaps there was an issue with Docker Hub at the time you last tried. I've seen timeouts there occasionally.
* Check that you have DNS resolution to the Docker Hub from the machine throwing errors: `dig index.docker.io`

I also suggest that you use a version tag rather than `latest` tag. I have the project on autobuild from Github and I haven't found a great way to manage 'latest' with an autobuild setup, so I make no guarantees about latest. :blush: Version tags will be solid.

**Comment by jomach** [comment]
Hi I've now tryed from other Internet connection and it works. strange... Internet was working fine... thanks for the reply !
